
spring:
  application:
    name: :neko-maid
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: "https://dashscope.aliyuncs.com/compatible-mode"
      chat:
        options:
          model: "deepseek-r1"
logging:
  level:
    org.springframework.ai: debug
    nekomaid: debug
